<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">$(MSBuildThisFileDirectory)project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">/home/ciyah/Desktop/HTBLabs/Fishy HTTP/.tools/.store/.stage/j1n30bpk.0lm</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">/home/ciyah/Desktop/HTBLabs/Fishy HTTP/.tools/.store/.stage/j1n30bpk.0lm</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">DotnetToolReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">6.3.0</NuGetToolVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="/home/ciyah/Desktop/HTBLabs/Fishy HTTP/.tools/.store/.stage/j1n30bpk.0lm/" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Pkgilspycmd Condition=" '$(Pkgilspycmd)' == '' ">/home/ciyah/Desktop/HTBLabs/Fishy HTTP/.tools/.store/.stage/j1n30bpk.0lm/ilspycmd/8.2.0.7535</Pkgilspycmd>
  </PropertyGroup>
</Project>